name: betterauth_flutter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/betterauth_flutter/**"
      - "packages/betterauth_dart/**"
      - ".github/workflows/betterauth_flutter.yaml"
  push:
    branches: [main]
    paths:
      - "packages/betterauth_flutter/**"
      - "packages/betterauth_dart/**"
      - ".github/workflows/betterauth_flutter.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: "3.41.1"
      working_directory: packages/betterauth_flutter
      min_coverage: 100
