name: betterauth_dart

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/betterauth_dart/**"
      - ".github/workflows/betterauth_dart.yaml"
  push:
    branches: [main]
    paths:
      - "packages/betterauth_dart/**"
      - ".github/workflows/betterauth_dart.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: "3.11.0"
      working_directory: packages/betterauth_dart
      min_coverage: 100
      coverage_excludes: "*.g.dart"

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: packages/betterauth_dart
